# Generated by Django 5.0.4 on 2024-05-06 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='type',
            new_name='org_type',
        ),
    ]
