# Generated by Django 5.0.4 on 2024-05-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_type_organization_org_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='needs',
            name='need1',
        ),
        migrations.RemoveField(
            model_name='needs',
            name='need2',
        ),
        migrations.RemoveField(
            model_name='needs',
            name='need3',
        ),
        migrations.RemoveField(
            model_name='needs',
            name='organization_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='org_id',
        ),
        migrations.AddField(
            model_name='admin',
            name='phone',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='phone',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='needs',
            name='clothes',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='needs',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='needs',
            name='educational',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='needs',
            name='food',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='needs',
            name='medicine',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='needs',
            name='org_username',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='disapproved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='upi_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='verifiername',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='approvefromorg',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='org_username',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='advertise',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='donor_username',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
